version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/api"
      - "/ParseDocs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[nuget]"      
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[npm]"
  - package-ecosystem: "docker"    
    directories:
      - "/api"
      - "/client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker]"
