//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class U6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal U6() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("api.Resources.U6", typeof(U6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Desc_FrackingSmasher_C&quot;: {
        ///    &quot;slug&quot;: &quot;resource_well_pressurizer&quot;,
        ///    &quot;name&quot;: &quot;Resource Well Pressurizer&quot;,
        ///    &quot;power&quot;: 150,
        ///    &quot;area&quot;: 400,
        ///    &quot;buildCost&quot;: [
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_Wire_C&quot;,
        ///        &quot;quantity&quot;: 200
        ///      },
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_Rubber_C&quot;,
        ///        &quot;quantity&quot;: 50
        ///      },
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_SteelPlateReinforced_C&quot;,
        ///        &quot;quantity&quot;: 50
        ///      },
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_Motor_C&quot;,
        ///        &quot;quantity&quot;: 50
        ///      } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string buildings {
            get {
                return ResourceManager.GetString("buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Desc_Crystal_C&quot;: &quot;Desc_Crystal_C&quot;,
        ///  &quot;Desc_Crystal_mk2_C&quot;: &quot;Desc_Crystal_mk2_C&quot;,
        ///  &quot;Desc_Crystal_mk3_C&quot;: &quot;Desc_Crystal_mk3_C&quot;,
        ///  &quot;Desc_Gift_C&quot;: &quot;Desc_Gift_C&quot;,
        ///  &quot;Desc_HogParts_C&quot;: &quot;Desc_HogParts_C&quot;,
        ///  &quot;Desc_SpitterParts_C&quot;: &quot;Desc_SpitterParts_C&quot;,
        ///  &quot;Desc_FlowerPetals_C&quot;: &quot;Desc_FlowerPetals_C&quot;,
        ///  &quot;Desc_Leaves_C&quot;: &quot;Desc_Leaves_C&quot;,
        ///  &quot;Desc_Mycelia_C&quot;: &quot;Desc_Mycelia_C&quot;,
        ///  &quot;Desc_Wood_C&quot;: &quot;Desc_Wood_C&quot;,
        ///  &quot;Desc_HatcherParts_C&quot;: &quot;Desc_HatcherParts_C&quot;,
        ///  &quot;Desc_StingerParts_C&quot;: &quot;Desc_StingerParts_C&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string handGatheredItems {
            get {
                return ResourceManager.GetString("handGatheredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Desc_Beacon_C&quot;: {
        ///    &quot;slug&quot;: &quot;beacon&quot;,
        ///    &quot;name&quot;: &quot;Beacon&quot;,
        ///    &quot;sinkPoints&quot;: 320,
        ///    &quot;usedInRecipes&quot;: [
        ///      &quot;Recipe_Alternate_NuclearFuelRod_1_C&quot;
        ///    ],
        ///    &quot;producedFromRecipes&quot;: [
        ///      &quot;Recipe_Alternate_Beacon_1_C&quot;,
        ///      &quot;Recipe_Beacon_C&quot;
        ///    ],
        ///    &quot;isFicsmas&quot;: false
        ///  },
        ///  &quot;Desc_PortableMiner_C&quot;: {
        ///    &quot;slug&quot;: &quot;portable_miner&quot;,
        ///    &quot;name&quot;: &quot;Portable Miner&quot;,
        ///    &quot;sinkPoints&quot;: 56,
        ///    &quot;usedInRecipes&quot;: [],
        ///    &quot;producedFromRecipes&quot;: [
        ///      &quot;Recipe_Alternate_AutomatedMiner_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Recipe_Alternate_ClassicBattery_C&quot;: {
        ///    &quot;slug&quot;: &quot;alternate_classic_battery_recipe&quot;,
        ///    &quot;name&quot;: &quot;Alternate: Classic Battery&quot;,
        ///    &quot;isAlternate&quot;: true,
        ///    &quot;ingredients&quot;: [
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_Sulfur_C&quot;,
        ///        &quot;perMinute&quot;: 45
        ///      },
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_AluminumPlate_C&quot;,
        ///        &quot;perMinute&quot;: 52.5
        ///      },
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_Plastic_C&quot;,
        ///        &quot;perMinute&quot;: 60
        ///      },
        ///      {
        ///        &quot;itemClass&quot;: &quot;Desc_Wire_C&quot;,
        ///        &quot;perMinute&quot;: 9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recipes {
            get {
                return ResourceManager.GetString("recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Desc_Sulfur_C&quot;: {
        ///    &quot;itemClass&quot;: &quot;Desc_Sulfur_C&quot;,
        ///    &quot;maxExtraction&quot;: 6840,
        ///    &quot;relativeValue&quot;: 1028
        ///  },
        ///  &quot;Desc_Coal_C&quot;: {
        ///    &quot;itemClass&quot;: &quot;Desc_Coal_C&quot;,
        ///    &quot;maxExtraction&quot;: 30900,
        ///    &quot;relativeValue&quot;: 227
        ///  },
        ///  &quot;Desc_OreCopper_C&quot;: {
        ///    &quot;itemClass&quot;: &quot;Desc_OreCopper_C&quot;,
        ///    &quot;maxExtraction&quot;: 28860,
        ///    &quot;relativeValue&quot;: 243
        ///  },
        ///  &quot;Desc_OreGold_C&quot;: {
        ///    &quot;itemClass&quot;: &quot;Desc_OreGold_C&quot;,
        ///    &quot;maxExtraction&quot;: 11040,
        ///    &quot;relativeValue&quot;: 637
        ///  },
        ///  &quot;Desc_OreIron_C&quot;: {
        ///    &quot;itemC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resources {
            get {
                return ResourceManager.GetString("resources", resourceCulture);
            }
        }
    }
}
