using './api-containerapp.module.bicep'

param api_containerimage = '{{ .Image }}'
param api_blue_revision = '{{ .Env.BLUE_REVISION }}'
param api_containerport = '{{ targetPortOrDefault 8080 }}'
param api_identity_outputs_clientid = '{{ .Env.API_IDENTITY_CLIENTID }}'
param api_identity_outputs_id = '{{ .Env.API_IDENTITY_ID }}'
param cosmos_db_outputs_connectionstring = '{{ .Env.COSMOS_DB_CONNECTIONSTRING }}'
param env_outputs_azure_container_apps_environment_default_domain = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param env_outputs_azure_container_apps_environment_id = '{{ .Env.ENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param env_outputs_applicationinsights_connection_string = '{{ .Env.ENV_APPLICATIONINSIGHTS_CONNECTION_STRING }}'
