//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class U8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal U8() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("api.Resources.U8", typeof(U8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Desc_FrackingSmasher_C&quot;:{&quot;slug&quot;:&quot;resource_well_pressurizer&quot;,&quot;name&quot;:&quot;Resource Well Pressurizer&quot;,&quot;power&quot;:150,&quot;area&quot;:400,&quot;buildCost&quot;:[{&quot;itemClass&quot;:&quot;Desc_Wire_C&quot;,&quot;quantity&quot;:200},{&quot;itemClass&quot;:&quot;Desc_Rubber_C&quot;,&quot;quantity&quot;:50},{&quot;itemClass&quot;:&quot;Desc_SteelPlateReinforced_C&quot;,&quot;quantity&quot;:50},{&quot;itemClass&quot;:&quot;Desc_Motor_C&quot;,&quot;quantity&quot;:50}],&quot;isFicsmas&quot;:false},&quot;Desc_FrackingExtractor_C&quot;:{&quot;slug&quot;:&quot;resource_well_extractor&quot;,&quot;name&quot;:&quot;Resource Well Extractor&quot;,&quot;power&quot;:0,&quot;area&quot;:16,&quot;buildCost&quot;:[{&quot;itemClass&quot;:&quot;Desc_SteelPlate_C&quot;,&quot;quantity&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string buildings {
            get {
                return ResourceManager.GetString("buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Desc_Crystal_C&quot;:&quot;Desc_Crystal_C&quot;,&quot;Desc_Crystal_mk2_C&quot;:&quot;Desc_Crystal_mk2_C&quot;,&quot;Desc_Crystal_mk3_C&quot;:&quot;Desc_Crystal_mk3_C&quot;,&quot;Desc_FlowerPetals_C&quot;:&quot;Desc_FlowerPetals_C&quot;,&quot;Desc_Gift_C&quot;:&quot;Desc_Gift_C&quot;,&quot;Desc_HatcherParts_C&quot;:&quot;Desc_HatcherParts_C&quot;,&quot;Desc_HogParts_C&quot;:&quot;Desc_HogParts_C&quot;,&quot;Desc_Leaves_C&quot;:&quot;Desc_Leaves_C&quot;,&quot;Desc_Mycelia_C&quot;:&quot;Desc_Mycelia_C&quot;,&quot;Desc_SpitterParts_C&quot;:&quot;Desc_SpitterParts_C&quot;,&quot;Desc_StingerParts_C&quot;:&quot;Desc_StingerParts_C&quot;,&quot;Desc_Wood_C&quot;:&quot;Desc_Wood_C&quot;}.
        /// </summary>
        internal static string handGatheredItems {
            get {
                return ResourceManager.GetString("handGatheredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Desc_AlienDNACapsule_C&quot;:{&quot;slug&quot;:&quot;alien_dna_capsule&quot;,&quot;name&quot;:&quot;Alien DNA Capsule&quot;,&quot;sinkPoints&quot;:0,&quot;usedInRecipes&quot;:[],&quot;producedFromRecipes&quot;:[&quot;Recipe_AlienDNACapsule_C&quot;],&quot;isFicsmas&quot;:false},&quot;Desc_AlienProtein_C&quot;:{&quot;slug&quot;:&quot;alien_protein&quot;,&quot;name&quot;:&quot;Alien Protein&quot;,&quot;sinkPoints&quot;:0,&quot;usedInRecipes&quot;:[&quot;Recipe_AlienDNACapsule_C&quot;,&quot;Recipe_Biomass_AlienProtein_C&quot;],&quot;producedFromRecipes&quot;:[&quot;Recipe_Protein_Stinger_C&quot;,&quot;Recipe_Protein_Spitter_C&quot;,&quot;Recipe_Protein_Hog_C&quot;,&quot;Recipe_Protein_Crab_C&quot;],&quot;isFicsmas&quot;:false},&quot;Desc_AluminaSolution_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Recipe_IronPlate_C&quot;:{&quot;slug&quot;:&quot;iron_plate_recipe&quot;,&quot;name&quot;:&quot;Iron Plate&quot;,&quot;isAlternate&quot;:false,&quot;ingredients&quot;:[{&quot;itemClass&quot;:&quot;Desc_IronIngot_C&quot;,&quot;perMinute&quot;:30}],&quot;products&quot;:[{&quot;itemClass&quot;:&quot;Desc_IronPlate_C&quot;,&quot;perMinute&quot;:20}],&quot;producedIn&quot;:&quot;Desc_ConstructorMk1_C&quot;,&quot;isFicsmas&quot;:false},&quot;Recipe_IronRod_C&quot;:{&quot;slug&quot;:&quot;iron_rod_recipe&quot;,&quot;name&quot;:&quot;Iron Rod&quot;,&quot;isAlternate&quot;:false,&quot;ingredients&quot;:[{&quot;itemClass&quot;:&quot;Desc_IronIngot_C&quot;,&quot;perMinute&quot;:15}],&quot;products&quot;:[{&quot;itemClass&quot;:&quot;Desc_IronRod_C&quot;,&quot;perMinute&quot;:15}],&quot;producedIn&quot;:&quot;Desc_ConstructorMk1_C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recipes {
            get {
                return ResourceManager.GetString("recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Desc_Water_C&quot;:{&quot;itemClass&quot;:&quot;Desc_Water_C&quot;,&quot;maxExtraction&quot;:null,&quot;relativeValue&quot;:1},&quot;Desc_OreIron_C&quot;:{&quot;itemClass&quot;:&quot;Desc_OreIron_C&quot;,&quot;maxExtraction&quot;:70380,&quot;relativeValue&quot;:100},&quot;Desc_Stone_C&quot;:{&quot;itemClass&quot;:&quot;Desc_Stone_C&quot;,&quot;maxExtraction&quot;:52860,&quot;relativeValue&quot;:133},&quot;Desc_Coal_C&quot;:{&quot;itemClass&quot;:&quot;Desc_Coal_C&quot;,&quot;maxExtraction&quot;:30900,&quot;relativeValue&quot;:227},&quot;Desc_Sulfur_C&quot;:{&quot;itemClass&quot;:&quot;Desc_Sulfur_C&quot;,&quot;maxExtraction&quot;:6840,&quot;relativeValue&quot;:1028},&quot;Desc_LiquidOil_C&quot;:{&quot;itemClass&quot;:&quot;Desc_LiquidOil_C&quot;,&quot;maxExtraction&quot;:11700,&quot;relati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resources {
            get {
                return ResourceManager.GetString("resources", resourceCulture);
            }
        }
    }
}
