name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Restore NuGet dependencies
      run: dotnet restore
    - name: Restore npm dependencies
      run: npm install && npx update-browserslist-db@latest
      working-directory: ./client
    - name: Dotnet Build
      run: dotnet build --no-restore
    - name: Dotnet Test
      run: dotnet test --no-build --verbosity normal
    - name: NPM Build
      run: npm run build
      working-directory: ./client
